# This is a basic workflow to help you get started with Actions

name: Unit Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: use this action, test solution dir
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: WorkTimeCalculatorTest
          report_name: Unit Tests
          report_title: My Project Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
