# This is a basic workflow to help you get started with Actions

name: Unit Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: use this action, test solution dir
        if: ${{ !cancelled() }} 
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: WorkTimeCalculatorTest
          report_name: UnitTestsResults
          report_title: Unit Tests Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: unitTestResults.md
          skip_check_run: true
          gist_token: ${{ secrets.GITHUB_TOKEN }}
          gist_badge_label: 'Unit Tests: %Counters_passed%/%Counters_total%'
